# Dùng Node.js base image Debian-based (ổn định hơn Alpine cho native modules như 'sharp')
FROM node:20-slim

# Tạo thư mục làm việc
WORKDIR /app

# Copy các file cấu hình cần thiết
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY ecosystem.config.js .
COPY .env.development .
COPY ./src ./src
COPY ./openapi ./openapi

# Cài các gói cần thiết
RUN apt-get update && apt-get install -y ffmpeg python3 bash

# Cài PM2 toàn cục và các package trong app
RUN npm install pm2 -g
RUN npm install

# Build project
RUN npm run build

EXPOSE 4000

CMD ["pm2-runtime", "start", "ecosystem.config.js"]
